
services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --log-level info
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://${DATABASE_USER}:${DATABASE_PASSWORD}@db:${DATABASE_PORT}/${DATABASE_NAME}
      - DEBUG=false
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:16
    container_name: my-postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5433:${DATABASE_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
