
services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "5678:5678"
    environment:
      - DATABASE_URL=postgresql+psycopg2://${DATABASE_USER}:${DATABASE_PASSWORD}@db:${DATABASE_PORT}/${DATABASE_NAME}
      - DEBUG=${DEBUG}
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: my-postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:${DATABASE_PORT}"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:

