-- Users table
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR NOT NULL UNIQUE,
    hashed_password VARCHAR NOT NULL,
    avatar_url VARCHAR,
    balance FLOAT DEFAULT 0.0,
    tasks_created INTEGER DEFAULT 0,
    tasks_completed INTEGER DEFAULT 0,
    is_verified BOOLEAN DEFAULT FALSE,
    rating FLOAT
);

-- Messages table
CREATE TABLE messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    sender_id UUID REFERENCES users(id),
    receiver_id UUID REFERENCES users(id),
    content VARCHAR NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tasks table
CREATE TABLE tasks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title VARCHAR NOT NULL,
    description VARCHAR NOT NULL,
    location VARCHAR,
    price FLOAT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    category VARCHAR NOT NULL,
    status VARCHAR NOT NULL,
    has_responses BOOLEAN DEFAULT FALSE,
    is_remote BOOLEAN DEFAULT FALSE,
    create_date TIMESTAMP NOT NULL,
    user_id UUID REFERENCES users(id)
);
